### ISSUE TITLE
Customization editor let us save even though you got a feature that require "at least one" child 

### ISSUE THREAD

**Issue by Falgu9** [Mobioos/Mobioos-Forge#2]
**Describe the bug**
Customization editor let us save even though you got a feature that require "at least one" child 

**To Reproduce**
1. In the feature model, create a feature with "Children rule" to "At least one" and create 2 or more child to the feature.
2. Then go to the Customization menu, create a new one, select the feature and not his child. You can see that you can save even though a child is required.

**Expected behavior**
Normally, the Customization menu doesn't let you save.

**Desktop (please complete the following information):**
 - OS: MacOS 13.1 M1
 - Mobioos Forge version: 2.1.2
 - VScode version: 1.74.3

**Comment by KarimGhallab** [comment]
Thanks for the feedback, the issue has been reproduced and will be fixed in the next release.
