### ISSUE TITLE
Ressource Validation give a wrong behavior

### ISSUE THREAD

**Issue by S-Mazigh** [Mobioos/Mobioos-Forge#3]
**Describe the bug**
If a resource file marker is validated, it cannot be configured anymore. 

**To Reproduce**
1. Create a resource file feature.
2. Create a marker on the path.
3. Validate the marker.
4. Now the path of the resource cannot be configured anymore.

**Expected behavior**
The generated variant have the same resource path as the original, the new path given in the configuration is ignored.

**Screenshots or event better video**
A video showing this behavior with the calculator example.
https://mega.nz/file/TcpgCA7R#nYmcZQlt0OtGb8PaE23THlq-8M1ZcVlRTI4WrpKgtKA

**Desktop (please complete the following information):**
 - OS: Linux mint 21.1 x86_64
 - Mobioos Forge version: v2.1.2
 - VScode version: 1.74.2

**Comment by KarimGhallab** [comment]
Thanks for the feedback, the issue has been reproduced and will be fixed in the next release.

**Comment by KarimGhallab** [comment]
Fixed with version 2.1.3 of Mobioos Forge.
