### ISSUE TITLE
"MF: Setting up the Customization Editor..." stuck 

### ISSUE THREAD

**Issue by ClementCallendret** [Mobioos/Mobioos-Forge#7]
**Describe the bug**
Im stuck on the loading screen "MF: Setting up the Customization Editor..." 
**To Reproduce**
1. Double click on any "Customization Scenarios" or try to modify one or create one.
2. Now im stuck with a loading screen "MF: Setting up the Customization Editor..." 

**Expected behavior**
I was expecting the file to load or to get an error.

**Screenshotsor event better video**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - Mobioos Forge version: 2.2.2
 - VScode version: 1.79.1
 - JDK 20
 -
**Additional context**
I try on a personnal projet and i was stuck with this problem.
So i try the Notepad Demo and got the same bug.
I already reset my vscode.
I update my JDK to the latest (20 atm).
It work on another Windows 11 computer.
Java is setup properly and works on others projects.
I have downloaded the 2 extensions recommended ( Language Support for Java(TM) by Red Hat and Debugger for java)

**Comment by KarimGhallab** [comment]
Hi, thanks for your feedback!
I managed to reproduce the problem, it seems that starting from version 22.04, ubuntu started to embed version 3.0 of libssl. However, forge requires version 1.0 to run correctly. You therefore need to install the correct version on your machine to run the customization editor.

I will send another message once I have found the packages.

**Comment by KarimGhallab** [comment]
Here are the packages you need to install to make Forge works properly:

- libssl-dev: Just run the command `sudo apt install libssl-dev`.
- libssl1.0.0: Manualy download the package corresponding to your architecture ([amd64](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb) or [i386](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0-dev_1.0.2n-1ubuntu5.13_i386.deb)), then install the package using the `sudo apt install` command.

Let me know if this fixed your issue!
