### ISSUE TITLE
Mobioos is unable to start

### ISSUE THREAD

**Issue by ClementCallendret** [Mobioos/Mobioos-Forge#8]
**Describe the bug**
Mobioos is unable to start.
**To Reproduce**
1. Change your VScode workspace by adding --user-data-dir D:\VScodeWorkspace to your vsCode shortcut
2. Start VScode with this shortcut (It's reset)
3. Install mobioos and all the extensions needed
4. Click on mobioos tab, and nothing happens when you press the 4 buttons.
5. When you want to refresh it, you get an error "Error running command mobioos-forge.variabilityModel.init: command 'mobioos-forge.variabilityModel.init' not found. This is likely caused by the extension that contributes mobioos-forge.variabilityModel.init."

**Expected behavior**
I exepect it to work as it was before i change my workspace

**Screenshotsor event better video**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Mobioos Forge version: 2.2.2
 - VScode version: 1.79.2

**Additional context**
It was working perfectly fine before i change the workspace
All other extensions works, except this one.

**Comment by ClementCallendret** [comment]
Edit :
I removed VScode + delete code Appdata + delete .mobioosforge file 
I reinstalled VScode with default workspace and reinstall extensions
Mobioos still doesn't work with the same error when clicking on refresh

**Comment by tziadi** [comment]
Please follow the steps below to remove and reinstall the Mobioos Forge extension in VSCode:

- Remove the Mobioos Forge extension from your VSCode.
- Delete the "mobioos.mobioos-forge-2.2.2" folder located inside "YourHome/.vscode/extensions".
- Reinstall Mobioos Forge.

I hope this helps! Let me know if you have any further questions.

**Comment by KarimGhallab** [comment]
Thank you for the clear description. I successfully managed to reproduce the issue.
It seems that changing the user data directory breaks the credentials stored by vscode (see issues [#130893](https://github.com/microsoft/vscode/issues/130893) and [#179202](https://github.com/microsoft/vscode/issues/179202) from the vscode repo) preventing Forge to start-up properly.
To fix this issue, follow the those steps: 
1. Close all your instances of vscode.
2. Delete all the credentials locally stored by vscode by running the following PowerShell one-liner (given by the vscode team [here](https://code.visualstudio.com/docs/editor/settings-sync#_windows)) : `cmdkey /list | Select-String -Pattern "LegacyGeneric:target=(vscode.+)" | ForEach-Object { cmdkey.exe /delete $_.Matches.Groups[1].Value }`
3. Re-open your forge project in vscode and log yourself.

Hope this fixed your issue!

**Comment by ClementCallendret** [comment]
Thanks a lot !
It works perfectly fine now !
